FROM python:3.7.7-slim

#COPY . /opt/app
WORKDIR /opt/app

RUN set -ex \
	&& buildDeps="build-essential make libssl-dev libghc-zlib-dev libcurl4-gnutls-dev libexpat1-dev gettext unzip git nodejs npm" \
	&& apt-get update \
    && apt-get install -y $buildDeps --no-install-recommends \
    && rm -rf /var/lib/apt/lists/* \
    && pip install -U pip==18.1 pipenv==2018.10.13
    #&& pipenv install --system --deploy --ignore-pipfile

RUN npm i -g serverless \
    && npm i

