#!/bin/sh
source script/setup

echo "Removing uneeded files"
rm -vrf ./build ./dist ./*.pyc ./*.tgz ./*.egg-info ./out ./*/out ./.mypy_cache ./*/.mypy_cache */.pytest_cache .pytest_cache .serverless/*

echo "Installing dependencies"
pipenv install --dev
pipenv install

