#!/bin/sh
echo "Checking system depencies such as pip and pipenv"
if [[ `which pip3` = "pip3 not found" ]]
then
    curl https://bootstrap.pypa.io/get-pip.py | python
fi

if [[ `which pipenv` = "pipenv not found" ]]
then
    curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
fi
if [[ `which docker-compose` = "docker-compose not found" ]]
then
    pip install docker-compose
fi

