#!/bin/sh


if [ `uname` = "Darwin" ]
then
    echo "installing dependncies for MacOS"
    # check if has brew
    brew install redis-cli
else
    echo "installing dependencies for Debian like"
    apt-get install redis-server
fi

echo "Configuring user in redis to test"
redis-cli SET "ADMIN" "xyz"

echo "running test"
py.test -s -v --cov=./ --cov-report term-missing -v
